// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_voyageur_expriment = "CgkI8K76ptkHEAIQCQ"; // <GPGSID>
        public const string achievement_brindille_dinfinis = "CgkI8K76ptkHEAIQCA"; // <GPGSID>
        public const string achievement_ciel_toil = "CgkI8K76ptkHEAIQBg"; // <GPGSID>
        public const string achievement_poignet_de_couronnes__dbutant = "CgkI8K76ptkHEAIQAg"; // <GPGSID>
        public const string achievement_voyageur_spatiale = "CgkI8K76ptkHEAIQBw"; // <GPGSID>
        public const string achievement_une_toile__lhorizon = "CgkI8K76ptkHEAIQBQ"; // <GPGSID>
        public const string leaderboard_record_infinis = "CgkI8K76ptkHEAIQAQ"; // <GPGSID>
        public const string achievement_sac_de_couronnes__intermdiaire = "CgkI8K76ptkHEAIQAw"; // <GPGSID>
        public const string achievement_flope_de_couronnes__confirm = "CgkI8K76ptkHEAIQBA"; // <GPGSID>
}

